// hpsdr_p1.c — Minimal openHPSDR Protocol 1 IQ streamer for sBitx

// Sends baseband IQ from sBitx to a Protocol 1 SDR client on our network.
// Packets are sent inline without flow control or mutexes.
// Input is 48k IQ samples per second.
// I and Q values received are scaled up to make SDR apps happier
// Code generated by copilot AI as a demo only ... good luck!  Mike/KB2ML

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <pthread.h>

#define HPSDR_PORT 1024
#define HPSDR_PKT_SIZE 1032
#define SAMPLES_PER_PACKET 126

static int hpsdr_sock = -1;
static struct sockaddr_in stream_dest;
static volatile int client_active = 0;
static volatile int running = 0;
static uint32_t tx_seq = 0;
static pthread_t poll_thread;

// IQ accumulation buffer for 126 samples (48kHz)
static double iq_buf_i[SAMPLES_PER_PACKET];
static double iq_buf_q[SAMPLES_PER_PACKET];
static int iq_buf_count = 0;
static double hpsdr_iq_gain = 0.1;  // <<<<< add gain to I and Q data going out

extern void remote_execute(char *command);
extern int freq_hdr;
extern int in_tx;

// --- Packet construction & inline transmission ------------------------------

static void build_and_send_packet(void)
{
    uint8_t pkt[HPSDR_PKT_SIZE];
    memset(pkt, 0, sizeof(pkt));

    // EP6 Header
    pkt[0] = 0xEF;
    pkt[1] = 0xFE;
    pkt[2] = 0x01;
    pkt[3] = 0x06;
    pkt[4] = (tx_seq >> 24) & 0xFF;
    pkt[5] = (tx_seq >> 16) & 0xFF;
    pkt[6] = (tx_seq >>  8) & 0xFF;
    pkt[7] =  tx_seq        & 0xFF;

    // Use current sequence to derive C&C address cadence, then increment once per packet
    uint32_t seq_for_cc = tx_seq++;

    // Two 512-byte frames
    for (int frame = 0; frame < 2; frame++) {
        uint8_t *fp = pkt + 8 + frame * 512;

        // Sync bytes
        fp[0] = 0x7F; fp[1] = 0x7F; fp[2] = 0x7F;

        // C&C control byte:
        // bit0 = MOX (TX flag), bits[5:1] = C0 address 0..31
        int cc_addr = (int)((seq_for_cc * 2 + frame) & 0x1F);
        fp[3] = (uint8_t)((cc_addr << 1) | (in_tx ? 1 : 0));

        // Fill control payload bytes [4..7] by C0 address
        // Keep this minimal but consistent with your current behavior.
        switch (cc_addr) {
            case 0:
                // Receiver 1 frequency (network byte order)
                fp[4] = (freq_hdr >> 24) & 0xFF;
                fp[5] = (freq_hdr >> 16) & 0xFF;
                fp[6] = (freq_hdr >>  8) & 0xFF;
                fp[7] =  freq_hdr        & 0xFF;
                break;

            case 1:
                // Basic status/sample-rate flags
                // Keep as zero for now (48k/no-overflow baseline in your prior code)
                fp[4] = 0x00;
                fp[5] = 0x00;
                fp[6] = 0x00;
                fp[7] = 0x00;
                break;

            case 2:
                // Mirror RX frequency here too to satisfy clients that watch addr 2 traffic
                fp[4] = (freq_hdr >> 24) & 0xFF;
                fp[5] = (freq_hdr >> 16) & 0xFF;
                fp[6] = (freq_hdr >>  8) & 0xFF;
                fp[7] =  freq_hdr        & 0xFF;
                break;

            default:
                // Leave zeros for unimplemented C&C addresses
                fp[4] = 0x00;
                fp[5] = 0x00;
                fp[6] = 0x00;
                fp[7] = 0x00;
                break;
        }

        // 63 IQ samples per frame
        for (int s = 0; s < 63; s++) {
            int idx = frame * 63 + s;
            uint8_t *sp = fp + 8 + s * 8;

            int32_t i_val = (int32_t)(iq_buf_i[idx] * 559240.0);
            if (i_val > 8388607) i_val = 8388607;
            if (i_val < -8388608) i_val = -8388608;

            int32_t q_val = (int32_t)(iq_buf_q[idx] * 559240.0);
            if (q_val > 8388607) q_val = 8388607;
            if (q_val < -8388608) q_val = -8388608;

            // Pack I (24-bit signed)
            sp[0] = (i_val >> 16) & 0xFF;
            sp[1] = (i_val >>  8) & 0xFF;
            sp[2] =  i_val        & 0xFF;

            // Pack Q (24-bit signed)
            sp[3] = (q_val >> 16) & 0xFF;
            sp[4] = (q_val >>  8) & 0xFF;
            sp[5] =  q_val        & 0xFF;

            // Mic sample (unused)
            sp[6] = 0;
            sp[7] = 0;
        }
    }

    if (client_active) {
        // DEBUG CODE TO SEE IF PKTS ARE GOING OUT
        static int dbg = 0;
        if ((dbg++ % 200) == 0) {
            int32_t max_i = 0, max_q = 0;
            for (int s = 0; s < 63 * 2; s++) {
                int off = 16 + s * 8; // first sample starts at pkt[16]
                int32_t i = (int32_t)((pkt[off+0] << 16) | (pkt[off+1] << 8) | pkt[off+2]);
                int32_t q = (int32_t)((pkt[off+3] << 16) | (pkt[off+4] << 8) | pkt[off+5]);
                if (i & 0x800000) i |= ~0xFFFFFF; // sign-extend 24b
                if (q & 0x800000) q |= ~0xFFFFFF;
                if (abs(i) > max_i) max_i = abs(i);
                if (abs(q) > max_q) max_q = abs(q);
            }
            printf("EP6 seq=%u maxI=%d maxQ=%d firstI=%02X%02X%02X firstQ=%02X%02X%02X\n",
               tx_seq - 1, max_i, max_q, pkt[16], pkt[17], pkt[18], pkt[19], pkt[20], pkt[21]);
        }
        sendto(hpsdr_sock, pkt, sizeof(pkt), 0,
               (struct sockaddr *)&stream_dest, sizeof(stream_dest));
    }
}

// --- Main Audio Thread Hook -------------------------------------------------

// Called continuously with 48kHz samples from the RX processing chain.
// No filtering or decimation required; just gain and packetization.
void hpsdr_send_iq(double *i_samples, double *q_samples, int n)
{
    if (!client_active || hpsdr_sock < 0) return;

    for (int k = 0; k < n; k++) {
        iq_buf_i[iq_buf_count] = i_samples[k] * hpsdr_iq_gain;
        iq_buf_q[iq_buf_count] = q_samples[k] * hpsdr_iq_gain;
        iq_buf_count++;

        if (iq_buf_count >= SAMPLES_PER_PACKET) {
            build_and_send_packet();
            iq_buf_count = 0;
        }
    }
}

// --- Command and Discovery (Background Thread) ------------------------------

static void handle_command(uint8_t *buf, int len, struct sockaddr_in *sender)
{
    if (len < 4) return;
    if (buf[0] != 0xEF || buf[1] != 0xFE) return;

    switch (buf[2]) {
    case 0x02:  // Discovery request
        {
            uint8_t reply[64];
            memset(reply, 0, sizeof(reply));

            reply[0] = 0xEF;
            reply[1] = 0xFE;
            reply[2] = 0x02;

            // 0x00 = available, 0x02 = in-use by another client
            int same_client =
                (client_active &&
                 sender->sin_addr.s_addr == stream_dest.sin_addr.s_addr &&
                 sender->sin_port        == stream_dest.sin_port);

            reply[3] = (client_active && !same_client) ? 0x02 : 0x00;

            // MAC + board/protocol identifiers (keep your current values for now)
            reply[4]  = 0x00; reply[5]  = 0x1C; reply[6]  = 0xC0;
            reply[7]  = 0xA2; reply[8]  = 0x22; reply[9]  = 0x5B;
            reply[10] = 0x06; // board type
            reply[11] = 0x25; // protocol version

            sendto(hpsdr_sock, reply, sizeof(reply), 0,
                   (struct sockaddr *)sender, sizeof(*sender));
        }
        break;

    case 0x04:  // Start / stop streaming
        {
            int start = ((buf[3] & 0x01) != 0) || (buf[3] != 0x00);
        
            if (start) {
                int same_dest =
                    client_active &&
                    sender->sin_addr.s_addr == stream_dest.sin_addr.s_addr;
        
                // keep forced 1024 if needed
                struct sockaddr_in new_dest = *sender;
                new_dest.sin_port = htons(HPSDR_PORT);
        
                if (!same_dest) {
                    stream_dest = new_dest;
                    tx_seq = 0;
                    iq_buf_count = 0;
                    printf("hpsdr: streaming STARTED cmd=%u to %s:%d\n",
                           (unsigned)buf[3], inet_ntoa(stream_dest.sin_addr), ntohs(stream_dest.sin_port));
                } else {
                    // repeated START from same client: keep streaming, do not reset seq/buffer
                    stream_dest = new_dest; // refresh anyway
                    printf("hpsdr: streaming keepalive START cmd=%u from %s\n",
                           (unsigned)buf[3], inet_ntoa(stream_dest.sin_addr));
                }
        
                client_active = 1;
            } else {
                client_active = 0;
                printf("hpsdr: streaming STOPPED cmd=%u\n", (unsigned)buf[3]);
            }
        }
        break;

    case 0x01:  // EP2 host commands
        {
            // Accept full 1032-byte packet, but also parse shorter packets that still contain one frame.
            if (len < 16) break; // not enough for header + sync + c0 + data

            int frames_available = 0;
            if (len >= 8 + 512 + 512) frames_available = 2;
            else if (len >= 8 + 512)  frames_available = 1;
            else                       frames_available = 0;

            for (int frame = 0; frame < frames_available; frame++) {
                uint8_t *fp = buf + 8 + frame * 512;
                if (fp[0] != 0x7F || fp[1] != 0x7F || fp[2] != 0x7F) continue;

                int c0   = fp[3];
                int addr = (c0 >> 1) & 0x1F;

                // Frequency updates are commonly seen on addr 0x00 or 0x02 depending on client/profile.
                if (addr == 0x00 || addr == 0x02) {
                    int f = ((int)fp[4] << 24) | ((int)fp[5] << 16) |
                            ((int)fp[6] <<  8) |  (int)fp[7];

                    if (f > 0 && f != freq_hdr) {
                        printf("hpsdr: remote set freq %d Hz (addr=%d)\n", f, addr);
                        char cmd[50];
                        snprintf(cmd, sizeof(cmd), "freq %d", f);
                        remote_execute(cmd);
                    }
                }

                // Track MOX from host control bit (optional but useful)
                in_tx = (c0 & 0x01) ? 1 : 0;
            }
        }
        break;

    default:
        break;
    }
}

static void *hpsdr_poll_thread(void *arg)
{
    uint8_t buf[2048];
    struct sockaddr_in sender;
    socklen_t sender_len;

    while (running) {
        sender_len = sizeof(sender);
        int n = recvfrom(hpsdr_sock, buf, sizeof(buf), 0,
                         (struct sockaddr *)&sender, &sender_len);
        if (n > 0) {
            handle_command(buf, n, &sender);
        }
    }
    return NULL;
}

// --- Initialization API -----------------------------------------------------

int hpsdr_init(void)
{
    hpsdr_sock = socket(AF_INET, SOCK_DGRAM, 0);
    if (hpsdr_sock < 0) return -1;

    int optval = 1;
    setsockopt(hpsdr_sock, SOL_SOCKET, SO_REUSEADDR, &optval, sizeof(optval));
    setsockopt(hpsdr_sock, SOL_SOCKET, SO_BROADCAST, &optval, sizeof(optval));

    struct sockaddr_in addr;
    memset(&addr, 0, sizeof(addr));
    addr.sin_family = AF_INET;
    addr.sin_port = htons(HPSDR_PORT);
    addr.sin_addr.s_addr = htonl(INADDR_ANY);

    if (bind(hpsdr_sock, (struct sockaddr *)&addr, sizeof(addr)) < 0) {
        close(hpsdr_sock);
        hpsdr_sock = -1;
        return -1;
    }

    struct timeval tv = { .tv_sec = 0, .tv_usec = 200000 };
    setsockopt(hpsdr_sock, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv));

    running = 1;
    return 0;
}

void hpsdr_stop(void)
{
    running = 0;
    client_active = 0;
    
    if (hpsdr_sock >= 0) {
        close(hpsdr_sock);
        hpsdr_sock = -1;
    }
}

int hpsdr_is_connected(void)
{
    return client_active;
}

void hpsdr_poll(void)
{
    static int started = 0;
    if (!started && running) {
        pthread_create(&poll_thread, NULL, hpsdr_poll_thread, NULL);
        started = 1;
    }
}
