// hpsdr_p1.c - Minimal openHPSDR Protocol 1 IQ streamer and command interface
// Command and discovery code based on hpsdrsim.c, the piHPSDR project's HPSDR simulator
// which is licensed as GPL 2.0
//
// Code generated by copilot AI as a demo only ... good luck!  Mike/KB2ML

#include "cw.h"
#include <arpa/inet.h>
#include <pthread.h>
#include <stdatomic.h>
#include <stdio.h>
#include <string.h>
#include <sys/socket.h>
#include <time.h>
#include <unistd.h>

#define HPSDR_PORT 1024
#define HPSDR_PKT_SIZE 1032
#define SAMPLES_PER_PACKET 126

// --- Packet pacing -----------------------------------------------------
// Lock-free single-producer/single-consumer ring buffer between the
// audio thread (producer, hpsdr_send_iq() - only ever writes q_head,
// only ever reads q_tail) and a dedicated pacer thread (consumer,
// hpsdr_pacer_thread() - only ever writes q_tail) that sends one packet
// every ~1.3ms at a steady, hardware-like cadence. Neither side can
// block the other: the producer always advances (dropping samples
// rather than waiting), the consumer drains whatever is available.
// Replaced an earlier inline-send design, and two reverted fix attempts
// (usleep() on the audio thread, a mutex-protected queue) that both
// caused continuous xruns for different reasons - see
// docs/04_remote_control_and_iq_output.md "Outbound (I/Q)" for the full
// history. IQ_QUEUE_CAP is a power of two so wraparound is a cheap
// bitmask instead of a modulo.
#define IQ_QUEUE_CAP                                                                              \
  4096 // samples (~42.7ms @ 96kHz) - comfortably
       // more than one bursty audio-thread block
       // (~1024-1040 samples), so the queue just
       // smooths the burst into an even drain
       // rather than ever running dry or full
       // in normal operation. Must stay a power
       // of two - see IQ_QUEUE_MASK.
#define IQ_QUEUE_MASK (IQ_QUEUE_CAP - 1)
#define PACKET_INTERVAL_NS 1312500L // 126 samples / 96000 Hz, exact

static int hpsdr_sock = -1;
static struct sockaddr_in stream_dest;
static volatile int client_active = 0;
static volatile int running = 0;
static uint32_t tx_seq = 0;
static pthread_t poll_thread;
static pthread_t pacer_thread;

// Lock-free SPSC IQ ring buffer between the audio thread (producer,
// hpsdr_send_iq()) and the pacer thread (consumer,
// hpsdr_pacer_thread()). q_head is written only by the producer, q_tail
// only by the consumer (or, on a fresh connect, caught up to q_head by
// the consumer at the poll thread's request - see reset_requested
// below); both sides read the other's index with acquire/release
// ordering so the sample data itself is always visible before the
// index publishing it is.
static double q_i[IQ_QUEUE_CAP];
static double q_q[IQ_QUEUE_CAP];
static atomic_uint q_head = 0;
static atomic_uint q_tail = 0;

// Set (by the poll thread, on a fresh EP1 START) to ask the pacer
// thread to drop whatever's queued. Only ever written by the poll
// thread and consumed (via exchange) by the pacer thread - neither the
// audio thread nor this flag's own writer ever touch q_head/q_tail
// directly, preserving the single-writer-per-index invariant above.
static atomic_int reset_requested = 0;

// One packet's worth of samples, filled from the queue by the pacer
// thread immediately before each build_and_send_packet() call.
static double iq_buf_i[SAMPLES_PER_PACKET];
static double iq_buf_q[SAMPLES_PER_PACKET];
static double hpsdr_iq_gain = 1.0; // <<<<< add gain to I and Q data going out

extern void radio_set_tx(int tx_on);
extern void radio_tune_to(uint32_t f); // same call hamlib.c "F" command uses
extern int
    freq_hdr; // hamlib.c "F" command and this file's EP2 handler both retune via radio_tune_to()
extern int in_tx; // read-only here - radio_set_tx() owns writing it

// Last non-zero RX1 (DDC0) frequency seen in EP2 C&C addr 0x02. Persisted
// because the client's C&C round-robin only populates this slot once every
// several frames - it's zero the rest of the time.
static uint32_t last_rx_freq = 0;

// Last non-zero TX VFO frequency seen in EP2 C&C addr 0x01. In SDR Console
// this is the operator's selected signal ("RX 1"); in apps like SPARK SDR
// it's always the spectrum center, same as last_rx_freq.
static uint32_t last_tx_freq = 0;

// --- Packet construction & inline transmission ------------------------------

static void build_and_send_packet(void) {
  uint8_t pkt[HPSDR_PKT_SIZE];
  memset(pkt, 0, sizeof(pkt));

  // EP6 Header
  pkt[0] = 0xEF;
  pkt[1] = 0xFE;
  pkt[2] = 0x01;
  pkt[3] = 0x06;
  pkt[4] = (tx_seq >> 24) & 0xFF;
  pkt[5] = (tx_seq >> 16) & 0xFF;
  pkt[6] = (tx_seq >> 8) & 0xFF;
  pkt[7] = tx_seq & 0xFF;

  // Use current sequence to derive C&C address cadence, then increment once per packet
  uint32_t seq_for_cc = tx_seq++;

  // Two 512-byte frames
  for (int frame = 0; frame < 2; frame++) {
    uint8_t *fp = pkt + 8 + frame * 512;

    // Sync bytes
    fp[0] = 0x7F;
    fp[1] = 0x7F;
    fp[2] = 0x7F;

    // C&C control byte:
    // bit0 = MOX (TX flag), bits[5:1] = C0 address 0..31
    int cc_addr = (int)((seq_for_cc * 2 + frame) & 0x1F);
    fp[3] = (uint8_t)((cc_addr << 1) | (in_tx ? 1 : 0));

    // Fill control payload bytes [4..7] by C0 address
    // Keep this minimal but consistent with your current behavior.
    switch (cc_addr) {
    case 0:
      // Receiver 1 frequency (network byte order)
      fp[4] = (freq_hdr >> 24) & 0xFF;
      fp[5] = (freq_hdr >> 16) & 0xFF;
      fp[6] = (freq_hdr >> 8) & 0xFF;
      fp[7] = freq_hdr & 0xFF;
      break;

    case 1:
      // Temperature (bits 31:16) / Forward Power (bits 15:0) on
      // real hardware. No such sensor here, so zero. Sample rate
      // has no readback field anywhere in EP6 - it's host-
      // requested only (EP2 addr 0, data bits [25:24]), and
      // minibitx doesn't parse that request, so the SDR app's
      // connection must be configured to match sound.c's
      // SAMPLE_RATE by hand.
      fp[4] = 0x00;
      fp[5] = 0x00;
      fp[6] = 0x00;
      fp[7] = 0x00;
      break;

    case 2:
      // Mirror RX frequency here too to satisfy clients that watch addr 2 traffic
      fp[4] = (freq_hdr >> 24) & 0xFF;
      fp[5] = (freq_hdr >> 16) & 0xFF;
      fp[6] = (freq_hdr >> 8) & 0xFF;
      fp[7] = freq_hdr & 0xFF;
      break;

    default:
      // Leave zeros for unimplemented C&C addresses
      fp[4] = 0x00;
      fp[5] = 0x00;
      fp[6] = 0x00;
      fp[7] = 0x00;
      break;
    }

    // 63 IQ samples per frame
    for (int s = 0; s < 63; s++) {
      int idx = frame * 63 + s;
      uint8_t *sp = fp + 8 + s * 8;

      int32_t i_val = (int32_t)(iq_buf_i[idx] * 559240.0);
      if (i_val > 8388607)
        i_val = 8388607;
      if (i_val < -8388608)
        i_val = -8388608;

      int32_t q_val = (int32_t)(iq_buf_q[idx] * 559240.0);
      if (q_val > 8388607)
        q_val = 8388607;
      if (q_val < -8388608)
        q_val = -8388608;

      // Pack I (24-bit signed)
      sp[0] = (i_val >> 16) & 0xFF;
      sp[1] = (i_val >> 8) & 0xFF;
      sp[2] = i_val & 0xFF;

      // Pack Q (24-bit signed)
      sp[3] = (q_val >> 16) & 0xFF;
      sp[4] = (q_val >> 8) & 0xFF;
      sp[5] = q_val & 0xFF;

      // Mic sample (unused)
      sp[6] = 0;
      sp[7] = 0;
    }
  }

  if (client_active) {
    sendto(hpsdr_sock, pkt, sizeof(pkt), 0, (struct sockaddr *)&stream_dest, sizeof(stream_dest));
  }
}

// --- Main Audio Thread Hook -------------------------------------------------

// Called once per audio-thread iteration (sound.c's SAMPLE_RATE is
// 96kHz; "48kHz" in an earlier version of this comment was stale) with
// that iteration's whole block of RX samples. No filtering or
// decimation required; just gain and packetization.
//
// This is sound.c's copy of the IQ for the HPSDR/UDP stream only - it
// knows nothing about usb_gadget.c, which sound.c feeds separately from
// its own copy. A no-op whenever no Protocol 1 client is connected.
//
// Producer side only: just append to the ring buffer and return. Must
// stay fast and never block or sleep - this runs on the real-time audio
// thread, which has to be back at its next snd_pcm_readi() well within
// one ~10.667ms period (see the packet-pacing comment above). All the
// actual pacing/sending happens in hpsdr_pacer_thread() instead.
void hpsdr_send_iq(double *i_samples, double *q_samples, int n) {
  if (!client_active || hpsdr_sock < 0)
    return;

  // Relaxed load: q_head is ours alone (we're the only writer), no
  // other thread's writes need to be ordered against it here.
  unsigned head = atomic_load_explicit(&q_head, memory_order_relaxed);
  // Acquire load: must happen-before reading q_i/q_q[tail..] below (it
  // doesn't here - we only compare against it - but acquire costs
  // nothing extra on the architectures this targets and keeps the
  // pairing consistent with the pacer thread's use of q_head).
  unsigned tail = atomic_load_explicit(&q_tail, memory_order_acquire);

  for (int k = 0; k < n; k++) {
    unsigned next_head = (head + 1) & IQ_QUEUE_MASK;
    if (next_head == tail) {
      // Ring buffer full - the pacer thread has fallen behind by
      // a full IQ_QUEUE_CAP worth of samples (~42.7ms). Drop this
      // sample rather than wait for the consumer or touch q_tail
      // (which only the pacer thread ever writes - see the
      // lock-free design note above). A brief IQ gap on the
      // network stream beats blocking this real-time thread.
      continue;
    }
    q_i[head] = i_samples[k] * hpsdr_iq_gain;
    q_q[head] = q_samples[k] * hpsdr_iq_gain;
    head = next_head;
  }

  // Release store: publishes both the new head index and everything
  // written to q_i/q_q above it, so the pacer thread's acquire load of
  // q_head is guaranteed to see the sample data too.
  atomic_store_explicit(&q_head, head, memory_order_release);
}

// --- Pacer Thread (Background) -----------------------------------------
//
// Drains the ring buffer at a steady, precise one-packet-per-1.3125ms
// cadence, fully decoupled from the audio thread's bursty production
// pattern. Uses an absolute wake time advanced by exactly one packet's
// worth of sample-time each iteration (not a repeated "sleep for X"),
// so the long-run average rate stays locked to the real sample rate
// with no cumulative drift no matter how long this runs.
static void *hpsdr_pacer_thread(void *arg) {
  (void)arg;
  struct timespec next;
  clock_gettime(CLOCK_MONOTONIC, &next);

  while (running) {
    next.tv_nsec += PACKET_INTERVAL_NS;
    while (next.tv_nsec >= 1000000000L) {
      next.tv_nsec -= 1000000000L;
      next.tv_sec++;
    }
    clock_nanosleep(CLOCK_MONOTONIC, TIMER_ABSTIME, &next, NULL);

    if (!client_active || hpsdr_sock < 0)
      continue;

    // A fresh EP1 START came in on the poll thread since we last
    // looked - catch q_tail up to the current q_head to drop
    // whatever was queued from before the connect, instead of the
    // poll thread touching q_tail itself (see reset_requested).
    if (atomic_exchange_explicit(&reset_requested, 0, memory_order_relaxed)) {
      unsigned h = atomic_load_explicit(&q_head, memory_order_acquire);
      atomic_store_explicit(&q_tail, h, memory_order_release);
    }

    unsigned head = atomic_load_explicit(&q_head, memory_order_acquire);
    unsigned tail = atomic_load_explicit(&q_tail, memory_order_relaxed);
    unsigned available = (head - tail) & IQ_QUEUE_MASK;

    if (available >= SAMPLES_PER_PACKET) {
      for (int s = 0; s < SAMPLES_PER_PACKET; s++) {
        iq_buf_i[s] = q_i[tail];
        iq_buf_q[s] = q_q[tail];
        tail = (tail + 1) & IQ_QUEUE_MASK;
      }
      atomic_store_explicit(&q_tail, tail, memory_order_release);
      build_and_send_packet();
    }
    // else: not enough data yet (e.g. just after connect, before
    // the queue has filled) - skip this tick and try again next.
  }
  return NULL;
}

// --- Command and Discovery (Background Thread) ------------------------------
//
// Inbound parsing below is modeled on hpsdrsim.c (the piHPSDR project's
// HPSDR hardware simulator - https://github.com/g0orx/pihpsdr), a mature
// reference for this side of the protocol. Getting it right against real
// clients took a few bugs shaking out on the bench - see
// docs/04_remote_control_and_iq_output.md "Inbound (EP2)" for the full
// history behind the strict length checks, the cc_addr==0 restriction on
// MOX below, and net_mox just below.

// The network's own last-seen MOX bit, tracked independently of in_tx
// (which cw.c's local key can also write) - see docs/04's "Inbound
// (EP2)" for the TX-latching bug this fixes. Only a real change in
// net_mox should ever trigger an action here.
static int net_mox = 0;

// Processes ONE 512-byte EP2 sub-frame. fp points at the frame's sync
// bytes (0x7F 0x7F 0x7F) - offset buf+8 for the first sub-frame and
// buf+8+512 for the second, matching both build_and_send_packet()'s own
// outbound layout and hpsdrsim.c's inbound offsets (buffer+11/buffer+523
// relative to the full packet - i.e. the same 8-byte header + 3 sync
// bytes before the C0 byte at fp[3]).
static void process_ep2_frame(uint8_t *fp) {
  if (fp[0] != 0x7F || fp[1] != 0x7F || fp[2] != 0x7F)
    return;

  // C&C register this frame carries - bits 6:1 of C0 (a 6-bit address,
  // 0-63; bit 7 is reserved and must not be folded into it). Matches
  // build_and_send_packet()'s own outbound addressing and the
  // Hermes-Lite2 protocol documentation.
  int cc_addr = (fp[3] >> 1) & 0x3F;

  // addr 0x01 = TX VFO frequency (operator's selected signal in SDR
  // Console; spectrum center in apps like SPARK SDR).
  if (cc_addr == 0x01) {
    uint32_t freq = ((uint32_t)fp[4] << 24) | ((uint32_t)fp[5] << 16) | ((uint32_t)fp[6] << 8) |
                    (uint32_t)fp[7];
    if (freq)
      last_tx_freq = freq;
  }

  // addr 0x02 = RX1 (DDC0) frequency.
  if (cc_addr == 0x02) {
    uint32_t freq = ((uint32_t)fp[4] << 24) | ((uint32_t)fp[5] << 16) | ((uint32_t)fp[6] << 8) |
                    (uint32_t)fp[7];
    if (freq)
      last_rx_freq = freq;
  }

  // MOX (PTT) is only acted on from C&C register (address) 0, unlike
  // hpsdrsim.c which reads it from every frame - bench-confirmed
  // requirement, see docs/04's "Inbound (EP2)".
  if (cc_addr != 0x00)
    return;

  int want_tx = (fp[3] & 0x01) ? 1 : 0;
  int net_mox_changed = (want_tx != net_mox);
  net_mox = want_tx;

  // Defer to the local key completely while it's holding TX (see
  // cw.c) - net_mox is still updated above so a value the network was
  // already sending doesn't look like a fresh edge once the key
  // releases.
  if (cw_tx_active())
    return;

  if (net_mox_changed && want_tx != in_tx) {
    if (want_tx) {
      // Retune to the operator's TX frequency before keying. Fall
      // back to the RX frequency if addr 0x01 was never received.
      uint32_t tx_freq = last_tx_freq ? last_tx_freq : last_rx_freq;
      if (tx_freq && tx_freq != (uint32_t)freq_hdr)
        radio_tune_to(tx_freq);
    }
    radio_set_tx(want_tx);
    printf("hpsdr: MOX -> %s\n", want_tx ? "TX on" : "TX off");
  }
}

static void handle_command(uint8_t *buf, int len, struct sockaddr_in *sender) {
  // Live frequency control lives exclusively in hamlib.c's rigctld-
  // compatible "F" command; this file only reports freq_hdr back as
  // outbound telemetry (see build_and_send_packet()).

  if (len < 4)
    return;
  if (buf[0] != 0xEF || buf[1] != 0xFE)
    return;

  switch (buf[2]) {
  case 0x02: // Discovery request - real clients always send exactly
             // 63 bytes (see hpsdrsim.c); anything else isn't a
             // genuine discovery packet and isn't worth answering.
  {
    if (len != 63)
      break;

    uint8_t reply[64];
    memset(reply, 0, sizeof(reply));

    reply[0] = 0xEF;
    reply[1] = 0xFE;
    reply[2] = 0x02;

    // 0x00 = available, 0x02 = in-use by another client
    int same_client = (client_active && sender->sin_addr.s_addr == stream_dest.sin_addr.s_addr &&
                       sender->sin_port == stream_dest.sin_port);

    reply[3] = (client_active && !same_client) ? 0x02 : 0x00;

    // MAC + board/protocol identifiers (keep your current values for now)
    reply[4] = 0x00;
    reply[5] = 0x1C;
    reply[6] = 0xC0;
    reply[7] = 0xA2;
    reply[8] = 0x22;
    reply[9] = 0x5B;
    reply[10] = 0x88; // board type: Hermes Lite2 (closest honest match)
    reply[11] = 0x25; // protocol version

    sendto(hpsdr_sock, reply, sizeof(reply), 0, (struct sockaddr *)sender, sizeof(*sender));
  } break;

  case 0x04: // Start / stop streaming - always exactly 64 bytes.
  {
    if (len != 64)
      break;

    int start = ((buf[3] & 0x01) != 0) || (buf[3] != 0x00);

    if (start) {
      int same_dest = client_active && sender->sin_addr.s_addr == stream_dest.sin_addr.s_addr &&
                      sender->sin_port == stream_dest.sin_port;

      // Reply to the sender's actual address:port - clients
      // receive the EP6 IQ stream on their own ephemeral port,
      // not HPSDR_PORT (1024, which is only where they send
      // commands to us).
      if (!same_dest) {
        stream_dest = *sender;
        tx_seq = 0;
        // Ask the pacer thread to drop whatever's queued -
        // it owns q_tail, so it does the actual reset (see
        // reset_requested's declaration above).
        atomic_store_explicit(&reset_requested, 1, memory_order_relaxed);
        printf("hpsdr: streaming STARTED cmd=%u to %s:%d\n", (unsigned)buf[3],
               inet_ntoa(stream_dest.sin_addr), ntohs(stream_dest.sin_port));
      } else {
        // repeated START from same client: keep streaming, do not reset seq/buffer
        stream_dest = *sender; // refresh anyway
      }

      client_active = 1;
    } else {
      client_active = 0;
      printf("hpsdr: streaming STOPPED cmd=%u\n", (unsigned)buf[3]);
    }
  } break;

  case 0x01: // EP2 host commands - always exactly 1032 bytes (8-byte
             // header + two 512-byte sub-frames). Anything else is a
             // torn or malformed packet, not real data - trying to
             // parse it anyway (the previous "accept a partial
             // packet" behavior) is what let nonsensical C&C
             // addresses through in the first place.
  {
    if (len != HPSDR_PKT_SIZE)
      break;
    process_ep2_frame(buf + 8);
    process_ep2_frame(buf + 8 + 512);

    // Follow the SDR app's tuning while receiving.
    if (!in_tx && last_rx_freq && last_rx_freq != (uint32_t)freq_hdr) {
      radio_tune_to(last_rx_freq);
      printf("hpsdr: remote tune -> %u Hz\n", last_rx_freq);
    }
  } break;

  default:
    break;
  }
}

static void *hpsdr_poll_thread(void *arg) {
  (void)arg;
  uint8_t buf[2048];
  struct sockaddr_in sender;
  socklen_t sender_len;

  while (running) {
    sender_len = sizeof(sender);
    int n = recvfrom(hpsdr_sock, buf, sizeof(buf), 0, (struct sockaddr *)&sender, &sender_len);
    if (n > 0) {
      handle_command(buf, n, &sender);
    }
  }
  return NULL;
}

// --- Initialization API -----------------------------------------------------

int hpsdr_init(void) {
  hpsdr_sock = socket(AF_INET, SOCK_DGRAM, 0);
  if (hpsdr_sock < 0)
    return -1;

  int optval = 1;
  setsockopt(hpsdr_sock, SOL_SOCKET, SO_REUSEADDR, &optval, sizeof(optval));
  setsockopt(hpsdr_sock, SOL_SOCKET, SO_BROADCAST, &optval, sizeof(optval));

  struct sockaddr_in addr;
  memset(&addr, 0, sizeof(addr));
  addr.sin_family = AF_INET;
  addr.sin_port = htons(HPSDR_PORT);
  addr.sin_addr.s_addr = htonl(INADDR_ANY);

  if (bind(hpsdr_sock, (struct sockaddr *)&addr, sizeof(addr)) < 0) {
    close(hpsdr_sock);
    hpsdr_sock = -1;
    return -1;
  }

  struct timeval tv = {.tv_sec = 0, .tv_usec = 200000};
  setsockopt(hpsdr_sock, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv));

  running = 1;
  return 0;
}

void hpsdr_stop(void) {
  running = 0;
  client_active = 0;

  if (hpsdr_sock >= 0) {
    close(hpsdr_sock);
    hpsdr_sock = -1;
  }
}

int hpsdr_is_connected(void) { return client_active; }

void hpsdr_poll(void) {
  static int started = 0;
  if (!started && running) {
    pthread_create(&poll_thread, NULL, hpsdr_poll_thread, NULL);
    pthread_create(&pacer_thread, NULL, hpsdr_pacer_thread, NULL);
    started = 1;
  }
}
